§color00r§,§color01r§,§color02r§,§color03r§,§color04r§,§color05r§,§color06r§,§color07r§,§color08r§,§color09r§,§color10r§,§color11r§,§color12r§,§color13r§,§color14r§,§color15r§
§color00g§,§color01g§,§color02g§,§color03g§,§color04g§,§color05g§,§color06g§,§color07g§,§color08g§,§color09g§,§color10g§,§color11g§,§color12g§,§color13g§,§color14g§,§color15g§
§color00b§,§color01b§,§color02b§,§color03b§,§color04b§,§color05b§,§color06b§,§color07b§,§color08b§,§color09b§,§color10b§,§color11b§,§color12b§,§color13b§,§color14b§,§color15b§
